collections:
  team:
    output: true
    sort_by: "ordering"
  former_team:
    output: true
    sort_by: "ordering"
  lectures:
    output: true
  projects:
    output: true
  publications:
baseurl: "/"
